### PR TITLE
Feature/dynamic labels

### PR DESCRIPTION
**Pull request by dionoid**
PR to merge the dynamic_labels branch into master

### CODE REVIEW

**Comment by andrew-davie** [comment]
Is this working?  I have a latest snapshot, built, and...
```
V = "ABC","DE"
    ECHO V
```
The result is "ABC". Not what I expected.

**Comment by andrew-davie** [comment]
Also, if you use

```
ABC,DE SET 0
```

The symbol table contains a label "ABC,DE"
Again, this doesn't seem right.

**Comment by msaarna** [comment]
Right now, the code always considers the first part of the label a "base" string, but further arguments would need to be quoted.

For me this: ABC,"DE" SET 0
creates a symbol "ABCDE" as expected.

But I did acknowledge a bug in our previous conversation thread on this, where DYNAMIC,LABEL SET # wasn't being handled correctly when the arguments aren't known yet. (as a ROM label on it's own, this functionality is working correctly)

This works as you're expecting, assuming ABCDE is a valid symbol...

V SET ABC,"DE"
    ECHO V

This is indeed not working...

V = ABC,"DE"
  ECHO V

...I need to see if = assignment can be reasonably supported.

**Comment by andrew-davie** [comment]
> For me this: ABC,"DE" SET 0
> creates a symbol "ABCDE" as expected.

Not for me. Hmmm.
I get the symbol "ABC,DE"

I'm using the 2.20.14.SNAPSHOT.
Is this correct?

**Comment by msaarna** [comment]
That's correct, but it might be a snapshot from the branch that was made for the large pull request, which probably didn't have dynamic labels in it.

Try grabbing the latest one [from the workflow actions](https://github.com/dasm-assembler/dasm/actions) and make sure it says "master" next to it.

**Comment by andrew-davie** [comment]
Thanks. Yes, that works as expected.
So I'm a bit confused about what's where and what I've been grabbing.
Anyway, at least I'm up and running now, thanks.

**Comment by msaarna** [comment]
You're welcome!

**Pull request merged**
