### PR TITLE
Contributing my modifications to DASM

### PR DESCRIPTION
**Pull request by thomas374b**
Hello,
I was using DASM already for a while. Are you interested in incorporating my modifications ? I created my own fork from the
latest snapshot 2.20.14 and tried to clean up things to find the lowest set of changes. The changes are:

- support for mc68hc908 controller family
- stack-pointer indexed address modi added
- larger hash-table size to avoid clashes when assembling projects with lots of symbols
- more strict checking of upper-/lowercase spelling to avoid clashes in symbols
- allow at-sign (@) to appear in label names
- allow '0x' prefixed hexadezimal notation, example '0x57' for '$57'..
- 2 bug workarounds

### CODE REVIEW

**Comment by andrew-davie** [comment]
Have done a quick test, and this new version is incompatible with the master, insofar as when I do an assembly with it of my current project - it doesn't work. In particular, here's the output...
```
../dasmx/dasm/bin/dasm ./chess.asm -E0 -S -p20 -l./chess.lst -f3 -v1 -s./chess.sym -o./chess.bin || (echo "mycommand failed $?"; exit 1)

START OF PASS: 1
INFO: Label 'TIA_BASE_ADDRESS' changed from $0040 to $0000
char = '{' 123 (-1: 32)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 95)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 95)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 32)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 43)
char = '}' 125 (-1: 48)
char = '{' 123 (-1: 43)
char = '}' 125 (-1: 48)
char = '{' 123 (-1: 43)
char = '}' 125 (-1: 48)
char = '{' 123 (-1: 43)
char = '}' 125 (-1: 48)
char = '{' 123 (-1: 43)
char = '}' 125 (-1: 48)
char = '{' 123 (-1: 43)
char = '}' 125 (-1: 48)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 48)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 48)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 48)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 48)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 48)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 48)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 48)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 48)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 48)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 48)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 48)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 48)
char = '{' 123 (-1: 95)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 50)
char = '{' 123 (-1: 95)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 43)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 43)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 105)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 105)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 105)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 50)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 50)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 50)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 50)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 50)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 50)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 50)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 50)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 50)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 50)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 50)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 50)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 50)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 50)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 50)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 50)
char = '{' 123 (-1: 43)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 43)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 35)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 35)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 35)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 35)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 43)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 43)
char = '}' 125 (-1: 49)
INFO: Label 'COLOUR_LINE_1' changed from $0086 to $00d6
INFO: Label 'COLOUR_LINE_2' changed from $0046 to $0066
INFO: Label 'COLOUR_LINE_3' changed from $00d8 to $0038
INFO: Label 'COLOUR_LINE_1' changed from $00d6 to $0024
INFO: Label 'COLOUR_LINE_2' changed from $0066 to $00a2
INFO: Label 'COLOUR_LINE_3' changed from $0038 to $0094
char = ':' 58 (-1: 79)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 32)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 0)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 60)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 62)
char = '}' 125 (-1: 49)
char = '{' 123 (-1: 40)
char = '}' 125 (-1: 55)
/bin/sh: line 1: 11094 Segmentation fault: 11  ../dasmx/dasm/bin/dasm ./chess.asm -E0 -S -p20 -l./chess.lst -f3 -v1 -s./chess.sym -o./chess.bin
mycommand failed 139
make: *** [chess.bin] Error 1
```

The listing file shows lots of errors that should not be errors.... for example...

```
vcs.h (51): error: Unknown Mnemonic 'IFNCONST'.
     51  0000 ????				      IFNCONST	TIA_BASE_ADDRESS
vcs.h (52): error: EQU: Value mismatch.
     52  0000 ????	       00 00	   TIA_BASE_ADDRESS =	0
vcs.h (53): error: Unknown Mnemonic 'ENDIF'.
```

and..
```
macro.h (57): error: Unknown Mnemonic 'MAC'.
     57  0298					      MAC	SLEEP	;usage: SLEEP n (n>1)
macro.h (57): error: Not enough args passed to Macro.
macro.h (58): error: Unknown Mnemonic 'SET'.
     58  0298				   .CYCLES    SET	{1}
     59  0298
macro.h (60): error: Unknown Mnemonic 'IF'.
     60  0298					      IF	.CYCLES < 2
 MACRO ERROR: 'SLEEP': Duration must be > 1
     61  0298					      ECHO	"MACRO ERROR: 'SLEEP': Duration must be > 1"
macro.h (62): error: Unknown Mnemonic 'ERR'.
     62  0298					      ERR
macro.h (63): error: Unknown Mnemonic 'ENDIF'.
     63  0298					      ENDIF
     64  0298
macro.h (65): error: Unknown Mnemonic 'IF'.
     65  0298					      IF	.CYCLES & 1
macro.h (66): error: Unknown Mnemonic 'IFNCONST'.
     66  0298					      IFNCONST	NO_ILLEGAL_OPCODES
     67  0298		       04 00		      nop	0
macro.h (68): error: Unknown Mnemonic 'ELSE'.
     68  0298					      ELSE
     69  029a		       24 00		      bit	VSYNC
macro.h (70): error: Unknown Mnemonic 'ENDIF'.
     70  029a					      ENDIF
macro.h (71): error: Unknown Mnemonic 'SET'.
     71  029a				   .CYCLES    SET	.CYCLES - 3
macro.h (72): error: Unknown Mnemonic 'ENDIF'.
     72  029a					      ENDIF
     73  029c
macro.h (74): error: Unknown Mnemonic 'REPEAT'.
     74  029c					      REPEAT	.CYCLES / 2
     75  029c		       ea		      nop
macro.h (76): error: Unknown Mnemonic 'REPEND'.
     76  029c					      REPEND
macro.h (77): error: Unknown Mnemonic 'ENDM'.
     77  029c					      ENDM
```


So, at this point... there seems to be a few problems with this version.

**Comment by dionoid** [comment]
Hi Thomas, thanks for reaching out! We are always interested in ways to improve DASM, so it's good to see new pull requests coming from the community.
However, your PR combines a list of features/changes, which makes it hard/inconvenient to review, discuss and validate.
Could you split up your changes into separate PRs? That will allow you to describe each change/feature in more detail. E.g. there is probably much more to say about "2 bug workarounds", or the reason for allowing the @-sign in labels.  Small and focused PRs allow the community to discuss, feedback, review, modify and eventually merge in changes. 

Please have a look at the 'Pull Request Etiquette' and I'm sure you'll get the point (a good write-up can be found here: https://gist.github.com/mikepea/863f63d6e37281e329f8)

Thanks for your time and effort!

**Comment by andrew-davie** [comment]
Yes, although my previous message may have appeared rather "dry", I would definitely like to state my appreciation for your work on the assembler, and would also encourage you to review and submit as suggested by @dionoid, above.  I have very very complex 6502 code which "severely" taxes the assembler - I will be happy to test any changes on my codebases. 
So ... thank you and welcome to our community. I hope we can get your changes in soon!

**Comment by thomas374b** [comment]
OK, I see the point. I've done all changes in one commit. I should split them up. I will restart from beginning ans send new pull requests for each single change with more comments.

**Pull request closed without merging**
