### PR TITLE
Add OpenBSD

### PR DESCRIPTION
**Pull request by gonzalo-**
Hello! Thanks for Dasm! I ported it to OpenBSD some months ago, I don't know if this is the right place or syntax to use, but feel free to change it.

### CODE REVIEW

**Comment by dionoid** [comment]
Hi, I'm wondering what code-changes you had to do, to port DASM over to OpenBSD?

**Comment by gonzalo-** [comment]
Hi!

Not much to be honest, you can see my patches here:

https://cvsweb.openbsd.org/ports/devel/dasm/patches/

I still need to fix some of the tests since you are using all the Linux ones, and on OpenBSD (probably other *BSD) some flags are not the same or are missing.

**Comment by gonzalo-** [comment]
No love for OpenBSD?

**Comment by dionoid** [comment]
README in master branch was updated to reflect DASM being built on BSD (OpenBSD, NetBSD)

**Pull request closed without merging**
